<div class="page-main-actions">
    <div class="store-switcher store-view">
        <form method="post" action="#" id="connector-key">
            <div class="actions dropdown closable">
                <label><span class="store-switcher-label">Secret Key: </span></label>
                <input id="connector-key" name="title" value="" title="Connector Key" type="text" class=" input-text admin__control-text required-entry _required" aria-required="true">
                <button type="submit" name="submit" value="Submit" class="primary">Submit</button>
            </div>
        </form>
    </div>

    <script>
        require([
            'jquery',
            'mage/mage'
        ], function($){

            var dataForm = $('#connector-key');
            var ignore = null;

            dataForm.mage('validation', {
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            }).find('input:text').attr('autocomplete', 'off');

        });
    </script>

</div>