<?php $choose_website_id = $this->getWebsiteIdFromUrl();?>
<div class="page-main-actions">
    <div class="connector-website">
        <form method="post" action="#" id="connector-website">
            <label class="website-label"><span class="website-switcher-label"><?php /* @escapeNotVerified */ echo __('Choose Website'); ?>: </span></label>
            <select id="choose-website" name="website" class="select admin__control-select">
                <?php foreach($this->getWebsiteCollection() as $website){?>
                    <option value="<?php echo $website->getId()?>"
                        <?php if($choose_website_id == $website->getId()){?>selected="selected"<?php }?>><?php echo $website->getName();?></option>
                <?php }?>
            </select>
        </form>
    </div>

    <script>
        require([
            'jquery',
            'mage/mage'
        ], function($){

            $('#connector-website').on('change', 'select', function (e) {
                var website_id = $(e.target).val();
                var url = '<?php echo $this->getFormUrl();?>website_id/'+website_id;
                $($.mage.redirect(url));
                return false;
            });
        });
    </script>

</div>