<?php $_simiconnector = $this->getCollection(); ?>
<?php if ($_simiconnector->getSize()): ?>
<div class="simiconnector_list_view">
    <?php foreach ($_simiconnector as $simiconnectorItem): ?>
        <div id="item_<?php echo $simiconnectorItem->getId() ?>" class="simiconnector_list_item">
            <h2>
                <a href="<?php echo $this->getItemUrl($simiconnectorItem) ?>">
                    <?php echo $this->escapeHtml($simiconnectorItem->getTitle()) ?>
                </a>
            </h2>

            <div class="simiconnector_item_subtitle">
                <?php echo $this->formatDate($simiconnectorItem->getPublishedAt()) ?> |
                <?php echo $this->escapeHtml($simiconnectorItem->getAuthor()) ?>
            </div>

            <?php if ($imageUrl = $this->getImageUrl($simiconnectorItem, 100)): ?>
               <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($simiconnectorItem->getTitle()); ?>" /></p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->getPager() ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no Simisimiconnector.'); ?></span></div>
<?php endif ?>
